### ISSUE TITLE
Policy on self-merges in this repository

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/state-signals#8]
Is it the intention of the this code-base to continue to allow anybody to post a PR and merge it without review?  If that is the case, I don't think the pbench code base will be able to rely on this work.  If that is not the case, can we consider using the repository rules to ensure reviews are done?

**Comment by Maxusmusti** [comment]
The policy has been changed to now require at least one review approval for all PRs, as well as test checks and up-to-date code w.r.t. the main branch
